In [1]:
import pandas as pd
#import dataset
df = pd.read_excel(r'C:\D_Drive\Reshma\MITSDE\FINAL_EXAM_KPMG\0d8b48bc-6faa-49c4-ac84-eefc02a620b1-housing-price.xlsx')
df.head()

,area_sqft,num_bedrooms,num_bathrooms,floor_number,age_of_property,distance_from_city_center_km,num_parking,num_balconies,property_price_lakhs
0,1460,5,4,9,9,4.2,0,3,132.23
1,1894,1,4,4,9,1.4,1,1,147.05
2,1730,5,4,6,26,15.8,0,0,120.01
3,1695,5,4,2,1,12.6,0,3,114.04
4,2238,3,1,6,29,14.3,0,0,123.92

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [7]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\reshm\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [53]:
# Train-test-split

x = df.drop(columns=["property_price_lakhs"]) #independent variable
y = df["property_price_lakhs"] #dependent variable

In [55]:
x.head()

,area_sqft,num_bedrooms,num_bathrooms,floor_number,age_of_property,distance_from_city_center_km,num_parking,num_balconies
0,1460,5,4,9,9,4.2,0,3
1,1894,1,4,4,9,1.4,1,1
2,1730,5,4,6,26,15.8,0,0
3,1695,5,4,2,1,12.6,0,3
4,2238,3,1,6,29,14.3,0,0

In [57]:
y.head()

0    132.23
1    147.05
2    120.01
3    114.04
4    123.92
Name: property_price_lakhs, dtype: float64

In [59]:
#splitting data into test and train dtaasets{20-80]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 31)
x_train.head()

,area_sqft,num_bedrooms,num_bathrooms,floor_number,age_of_property,distance_from_city_center_km,num_parking,num_balconies
545,679,2,4,3,0,13.2,2,3
215,1616,5,2,5,6,13.9,2,2
589,2424,4,2,6,0,17.9,0,2
582,2438,2,1,6,0,14.1,0,3
544,1772,2,2,5,21,4.7,0,2

In [61]:
#building  the model

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [67]:
#predicting based on test data
y_pred = model.predict(x_test)

In [69]:
#performance metrics
mse = mean_squared_error(y_test, y_pred)
mse

79.57049988131334

In [71]:
model.coef_

array([ 0.06032547,  4.60009802,  3.71325928,  1.43525279, -0.83371471,
       -1.23813704,  2.23376087,  1.42838748])

In [73]:
 model.intercept_

1.9823447274089716

In [76]:
#prediction
x1 = 5
x2 = 3
x3 = 4
x4 = 3
x5 = 8
x6 = 0
x7 = 3
x8 = 140.20

In [78]:
m1 = 0.06032547 
m2 = 4.60009802
m3 = 3.71325928
m4 = 1.43525279
m5 = -0.83371471
m6 = -1.23813704
m7 = 2.23376087
m8 = 1.42838748

In [80]:
c = 1.9823447274089716

In [82]:
y = (m1*x1)+(m2*x2)+(m3*x3)+(m4*x4)+(m5*x5)+(m6*x6)+(m7*x7)+(m8*x8)+c

In [84]:
y

235.53455125340895

In [91]:
# Model performance metrics R² value of the model
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)

In [94]:
print(f"R² Score: {r2}")

R² Score: 0.9617084595218497