In [10]:
import pandas as pd
#import dataset
df = pd.read_excel(r'C:\D_Drive\Reshma\MITSDE\CTC-Data-fresh.xlsx')
df.head()

,CTCoffered,LastCTC,Interview rating,Skill Set Index,Highest qualification,Total years of work exp
0,19,18,4,3,3,8.5
1,17,16,4,3,3,7.7
2,17,16,4,3,3,7.9
3,9,8,3,1,2,2.7
4,10,9,5,4,4,9.7

In [2]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [12]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\reshm\anaconda3\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\reshm\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [17]:
# Train-test-split

x = df.drop(columns=["CTCoffered"]) #independent variable
y = df["CTCoffered"] #dependent variable

In [19]:
x.head()

,LastCTC,Interview rating,Skill Set Index,Highest qualification,Total years of work exp
0,18,4,3,3,8.5
1,16,4,3,3,7.7
2,16,4,3,3,7.9
3,8,3,1,2,2.7
4,9,5,4,4,9.7

In [21]:
y.head()

0    19
1    17
2    17
3     9
4    10
Name: CTCoffered, dtype: int64

In [25]:
#splitting data into test and train dtaasets{20-80]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 31)
x_train.head()

,LastCTC,Interview rating,Skill Set Index,Highest qualification,Total years of work exp
68,10,3,1,2,3.0
149,14,5,4,4,10.4
180,7,3,1,2,2.6
130,19,3,2,2,5.4
33,8,5,4,4,9.5

In [27]:
#building  the model

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [35]:
#predicting based on test data
y_pred = model.predict(x_test)

In [39]:
#performance metrics
mse = mean_squared_error(y_test, y_pred)
mse

0.21084381663735008

In [41]:
model.coef_

array([ 0.55146459, -5.66202205,  0.49459056, -0.33632914,  1.66427836])

In [46]:
 model.intercept_

17.291935089686408

In [64]:
#prediction
x1 = 13.5
x2 = 3
x3 = 4
x4 = 3
x5 = 8

In [60]:
m1 = 0.55146459
m2 = -5.66202205
m3 = 0.49459056
m4 = -0.33632914
m5 = 1.66427836

In [48]:
c = 17.291935089686408

In [66]:
y = (m1*x1)+(m2*x2)+(m3*x3)+(m4*x4)+(m5*x5)+c

In [68]:
y

22.034242604686412