In [1]:
#import libraries

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_excel(r'C:\D_Drive\Reshma\EmpData.xlsx')
df.head()

,Attrition,DistanceFromHome,Education,JobSatisfaction,MonthlyIncome,PercentSalaryHike,PerformanceRating,YearsWithCurrManager
0,1,1,2,4,5993,11,3,5
1,0,8,1,2,5130,23,4,7
2,1,2,2,3,2090,15,3,0
3,0,3,4,3,2909,11,3,0
4,0,2,1,2,3468,12,3,2

In [3]:
# Defining independent and dependent variables

x = df.drop(columns=["Attrition"]) # independent variable
y = df["Attrition"] # dependent variable

#x = df.drop(columns=["CTCoffered"]) #independent variable
#y = df["CTCoffered"] #dependent variable

In [4]:
x.head()

,DistanceFromHome,Education,JobSatisfaction,MonthlyIncome,PercentSalaryHike,PerformanceRating,YearsWithCurrManager
0,1,2,4,5993,11,3,5
1,8,1,2,5130,23,4,7
2,2,2,3,2090,15,3,0
3,3,4,3,2909,11,3,0
4,2,1,2,3468,12,3,2

In [5]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Attrition, dtype: int64

In [6]:
#Splitting data into test and train datasets [20-80]

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 4)

In [8]:
x_train.head()

,DistanceFromHome,Education,JobSatisfaction,MonthlyIncome,PercentSalaryHike,PerformanceRating,YearsWithCurrManager
1316,2,4,4,5675,20,4,7
909,25,3,4,2994,12,3,1
1453,11,4,4,6652,13,3,0
1358,10,2,4,6583,11,3,4
157,9,3,2,3346,20,4,0

In [9]:
y_train.head()

1316    0
909     0
1453    0
1358    0
157     0
Name: Attrition, dtype: int64

In [10]:
x_test.head()

,DistanceFromHome,Education,JobSatisfaction,MonthlyIncome,PercentSalaryHike,PerformanceRating,YearsWithCurrManager
325,7,2,3,8943,24,4,9
1165,1,5,4,5743,11,3,2
1153,3,2,4,1569,12,3,0
1403,15,4,1,13341,12,3,10
1019,16,4,1,5647,13,3,2

In [11]:
y_test.head()

325     0
1165    0
1153    1
1403    0
1019    0
Name: Attrition, dtype: int64

In [14]:
#building model

model = LinearRegression()

In [16]:
model.fit(x_train,y_train)

LinearRegression()

In [18]:
# Predicting based on Test Data
y_pred = model.predict(x_test)

In [20]:
y_pred

array([ 4.37300741e-02,  1.34826144e-01,  2.11834246e-01,  1.21110639e-01,
        2.90618995e-01,  1.54020261e-01,  1.15577891e-01, -7.23108636e-02,
        7.36429736e-02,  1.44438594e-01,  1.71764194e-01,  1.17714656e-01,
        2.06493110e-02,  1.13211705e-01, -1.79700934e-02,  5.63569817e-02,
        2.15476100e-01,  1.06073871e-01,  1.70126902e-01,  1.12243097e-01,
        1.81040754e-01,  1.00241876e-01,  1.19431527e-01,  3.08437225e-01,
        3.61251635e-02,  2.29109697e-01,  3.05556226e-01,  1.52338529e-01,
        1.89639810e-01, -1.09057633e-01,  7.46593849e-02,  2.06455304e-01,
        7.25085281e-02,  3.03316560e-01,  2.16029240e-01,  2.01116678e-01,
        1.05547719e-02,  1.89382919e-01,  2.40517786e-01,  2.49775975e-01,
        1.37326969e-01,  1.94896819e-01,  8.67268586e-02,  1.49883634e-01,
        1.68561968e-01,  2.09456319e-01,  2.56045004e-01,  2.28384433e-01,
        2.04370752e-01,  2.62743739e-02,  1.62714991e-01,  2.60281966e-01,
        1.27387209e-01,  6.45296563e-02,  1.88035936e-01,  1.46279787e-01,
        3.67379751e-02,  2.32873736e-01,  3.26390403e-01,  1.61876328e-01,
        5.10071110e-02,  1.78848366e-01,  1.47897304e-01,  1.53247226e-01,
        5.91868258e-02,  9.79716753e-02,  1.39824204e-01,  2.58153399e-01,
        2.75751322e-01,  7.59456857e-02,  1.10274566e-01,  3.03165770e-01,
        8.25879940e-02,  1.80188774e-01, -2.49748815e-02,  3.66333381e-02,
        3.85687104e-02,  1.22179265e-01,  1.77890290e-01, -7.83975291e-02,
        2.73935135e-01,  2.64954403e-01,  1.03453498e-01,  2.16547690e-01,
        2.79996620e-01,  3.15869627e-01, -5.11328956e-02,  1.45978609e-01,
        1.41130934e-01,  2.24960856e-01,  6.86496136e-02,  9.99926982e-02,
        1.01895963e-01,  2.17248503e-01,  1.36750491e-02,  1.34380501e-01,
        2.99148095e-01,  1.76995738e-01,  1.51839081e-01,  3.50048883e-01,
        1.63947523e-01,  2.22050455e-01,  1.12977437e-01,  6.64921165e-02,
        2.31846007e-01,  3.19994670e-02,  3.12970697e-01,  1.81980925e-01,
        1.95173222e-01,  2.71091329e-01,  2.45041539e-02,  2.02018485e-01,
        2.72303429e-02,  2.42303099e-01,  1.58074671e-01,  9.11833039e-02,
        2.58419338e-01,  2.33795119e-01,  1.48224097e-01,  1.15956935e-01,
        2.94981403e-01,  3.03243803e-01,  4.95031068e-02,  2.76951442e-01,
        1.27215683e-01,  2.61144576e-01,  1.69951204e-01,  2.02922984e-01,
        2.48117989e-01,  1.69680672e-01,  1.16379984e-01, -3.86513058e-02,
        2.46044168e-01,  1.11362767e-01, -1.70689306e-02, -1.18538100e-03,
        8.18912038e-02,  4.06422433e-02,  1.60240664e-01,  1.58758072e-01,
        2.44038978e-01,  2.28688646e-01,  2.97874181e-01,  3.44217807e-02,
        1.72349779e-01,  1.65457246e-01,  4.78299867e-02,  1.58654659e-01,
        2.23888481e-01,  8.83030134e-02,  2.61685904e-01,  2.84311966e-02,
        3.08278348e-01,  7.69418145e-02,  2.00693608e-01,  2.55071356e-01,
       -5.79329517e-02,  3.70133981e-02,  3.03256252e-01,  1.76144980e-01,
        2.82529379e-01,  1.87945847e-01,  2.09038813e-01, -2.81822461e-04,
        2.41132339e-01,  5.85693822e-02,  2.38819108e-01,  1.56384742e-01,
        2.40814619e-01,  5.24819866e-02,  8.67402430e-02,  3.25554459e-01,
        1.76347691e-01,  3.04069003e-01,  7.37179522e-03,  1.64347727e-01,
       -3.61343463e-02,  1.82498067e-01,  3.45314233e-02,  1.70911492e-01,
        1.29195715e-01,  2.23517287e-01,  1.66971492e-01,  2.22005701e-01,
        1.01275036e-01,  1.42799217e-01,  1.72646793e-01,  1.05592559e-01,
        2.01448486e-01,  4.57671023e-02,  1.80743024e-01,  2.11871626e-01,
        2.77206465e-01,  2.68357396e-01,  1.53189302e-01,  2.18826790e-01,
        9.74962743e-02,  1.17500345e-01,  1.38060676e-01,  1.70160619e-01,
        1.12917466e-01,  1.37949855e-01,  6.49541579e-02,  1.62749831e-01,
        1.72568401e-01,  1.23322557e-01,  6.51197647e-02,  2.48863095e-01,
        6.32463090e-02,  3.55345877e-02,  1.26376891e-01,  7.25059611e-02,
        2.34721532e-01,  3.07063160e-03,  7.26868245e-02,  3.06928720e-01,
        1.83798946e-01,  1.13606235e-01,  1.97193063e-01,  1.74122954e-01,
        1.27279514e-01,  1.09111018e-01, -2.31998388e-02,  1.33915472e-01,
        2.75116676e-01,  1.60222609e-02,  3.23148048e-01,  1.09152606e-01,
        1.77845348e-01,  1.57397491e-01,  1.15088754e-01,  2.74869919e-01,
        2.78106260e-01,  2.15949440e-01,  3.22037381e-01,  1.42920311e-01,
        2.39992211e-01,  1.69502202e-01,  7.23587364e-02,  2.06504190e-01,
        8.07056894e-02,  2.39144718e-01,  3.01055146e-01,  1.96758433e-01,
       -1.18136818e-02,  1.91883325e-01,  8.36935168e-02,  2.38531293e-01,
        2.10586746e-01,  2.65095004e-01,  2.93989058e-01,  3.01312973e-01,
        1.85015914e-01,  2.54980268e-01,  9.85248180e-02,  2.92395898e-01,
        2.23899632e-01,  1.88927799e-01,  1.81096698e-01,  1.04319303e-01,
        1.99526788e-01, -4.76670599e-02,  1.76561814e-01,  1.37518839e-01,
        5.72683785e-02,  3.86207419e-02,  2.40196903e-01,  2.66450124e-01,
        2.51743959e-01, -5.62383066e-02,  8.55068574e-02,  1.29664060e-01,
        2.58784841e-01,  1.59932664e-01,  1.85237741e-01, -1.02138002e-01,
        8.45072991e-02,  1.76584761e-01,  2.84077718e-01,  9.89574333e-02,
        1.85778426e-01,  5.15591147e-02,  2.49977526e-01,  5.09727737e-02,
        1.39585107e-01,  2.35198303e-01,  1.32715375e-01,  3.09374757e-01,
        2.45598937e-01,  1.74237442e-01,  1.15879383e-01,  2.23829596e-01,
        1.96968999e-01,  1.20520559e-01])

In [22]:
# Performance Metrics
mse = mean_squared_error(y_test, y_pred)
mse

0.1197346666376244

In [26]:
model.coef_

array([ 2.18603283e-03, -5.12393652e-03, -4.32669911e-02, -8.98830547e-06,
       -6.39271446e-03,  4.05059361e-02, -1.30698769e-02])

In [30]:
model.intercept_

0.3578894016988098

In [32]:
#prediction

x1 = 9
x2 = 3
x3 = 4
x4 = 6500
x5 = 15
x6 = 4
x7 = 4

In [34]:
m1 = 2.18603283e-03
m2 = -5.12393652e-03
m3 = -4.32669911e-02
m4 = -8.98830547e-06
m5 = -6.39271446e-03
m6 = 4.05059361e-02
m7 = -1.30698769e-02

In [36]:
c = 0.3578894016988098

In [42]:
y = (m1*x1)+(m2*x2)+(m3*x3)+(m4*x4)+(m5*x5)+(m6*x6)+(m7*x7)+c

In [44]:
y

0.14455345755380977

In [46]:
#logistic regression

import numpy as np # import numericalpy lib for mathematical exp
#prob = e^y/(1+e^y) #formula for probablity
a = np.exp(y)

In [48]:
b = 1+a

In [50]:
prob = a/b

In [52]:
prob

0.5360755675622073